# Generated by Django 4.0.4 on 2022-05-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_album'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='album',
            name='posts',
            field=models.ManyToManyField(to='main_app.post'),
        ),
    ]
